import "./Main.scss";
import "./Card.scss";
import "./Experience.scss";
import "./Home.scss";
import "./About.scss";
import "./FormInput.scss";
import "./Form.scss";
import "./Button.scss";
import "./Success.scss";
import "./Footer.scss";
import "./SideBar.scss"
import "./Header.scss";
import "./Projects.scss";